apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "clickhouse.metadataLabels" . | nindent 4 }}
automountServiceAccountToken: true
