apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "http-server.metadataLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "http-server.selectorLabels" . | nindent 6 }}
  maxUnavailable: {{ .Values.maxUnavailable }}
