repository: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gorun/core/devcontainer
tag: 0.7.101
aliases:
  - # https://hub.docker.com/r/damianagape/gorun-devcontainer
    repository: damianagape/gorun-devcontainer
  - # https://github.com/users/damianagape/packages/container/package/gogcp-devcontainer
    repository: ghcr.io/damianagape/gorun-devcontainer
