apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "postgres.metadataLabels" . | nindent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-headless"
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "postgres.metadataLabels" . | nindent 8 }}
        {{- if .Values.extraPodLabels }}
        {{- toYaml .Values.extraPodLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configs: "{{ include "postgres.configsChecksum" . }}"
        {{- if .Values.extraPodAnnotations }}
        {{- toYaml .Values.extraPodAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      containers:
        - name: postgres-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config-envs"
            - secretRef:
                name: "{{ .Release.Name }}-config-envs"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          ports:
            - name: postgres-tcp
              containerPort: 5432
              protocol: TCP
          startupProbe:
            exec:
              command:
                - pg_isready
                - --host=127.0.0.1
                - --port=5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - --host=127.0.0.1
                - --port=5432
          livenessProbe:
            exec:
              command:
                - pg_isready
                - --host=127.0.0.1
                - --port=5432
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          securityContext: # container security context
            privileged: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            runAsUser: 999
            runAsGroup: 999
      securityContext: # pod security context
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.resources.requests.storage }}"
