apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "postgres.metadataLabels" $ | nindent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-headless"
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" $ | nindent 6 }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "postgres.metadataLabels" $ | nindent 8 }}
        {{- if .Values.extraPodLabels }}
        {{- toYaml .Values.extraPodLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/envs: "{{ include "postgres.envsChecksum" $ }}"
        {{- if .Values.extraPodAnnotations }}
        {{- toYaml .Values.extraPodAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      initContainers:
        - name: chown-volume
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["chown"]
          args: ["-R", "999:999", "/var/lib/postgresql"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            privileged: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-envs"
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-envs"
            - secretRef:
                name: "{{ .Release.Name }}-envs"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          ports:
            - name: server
              containerPort: 5432
              protocol: TCP
          startupProbe:
            exec:
              command:
                - pg_isready
                - --host=127.0.0.1
                - --port=5432
                - --username=${POSTGRES_USER}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - --host=127.0.0.1
                - --port=5432
                - --username=${POSTGRES_USER}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - --host=127.0.0.1
                - --port=5432
                - --username=${POSTGRES_USER}
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          securityContext: # container security context
            privileged: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            runAsUser: 999
            runAsGroup: 999
      securityContext: # pod security context
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "postgres.selectorLabels" $ | nindent 20 }}
                topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.resources.requests.storage }}"
