---
apiVersion: v1
kind: Namespace
metadata:
  name: o11y-prom-collector
  labels:
    app.kubernetes.io/component: prom-collector
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}

---
apiVersion: v1
kind: Secret
metadata:
  namespace: o11y-prom-collector
  name: prom-collector-envs
  labels:
    app.kubernetes.io/component: prom-collector
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}
data:
  {{- include "otel-collectors.envs" $ | nindent 4 }}

---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  namespace: o11y-prom-collector
  name: prom
  labels:
    app.kubernetes.io/component: prom-collector
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}
spec:
  config:
    {{- include "otel-collectors.promCollectorConfig" $ | nindent 4 }}
  envFrom:
  - secretRef:
      name: prom-collector-envs

  mode: statefulset
  replicas: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
  podAnnotations:
    checksum/envs: "{{ include "otel-collectors.envsChecksum" $ }}"
    prometheus.io/scrape: "false"
  observability:
    metrics:
      enableMetrics: false

  targetAllocator:
    enabled: true
    serviceAccount: prom-targetallocator
    replicas: 1
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
      limits: {}
    observability:
      metrics:
        enableMetrics: false

    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
      probeSelector: {}
      scrapeConfigSelector: {}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: o11y-prom-collector
  labels:
    app.kubernetes.io/component: prom-collector
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: o11y-otel-collector
subjects:
- kind: ServiceAccount
  namespace: o11y-prom-collector
  name: prom-collector

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: o11y-prom-collector
  name: prom-targetallocator
  labels:
    app.kubernetes.io/component: prom-targetallocator
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: o11y-prom-targetallocator
  labels:
    app.kubernetes.io/component: prom-targetallocator
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: o11y-otel-targetallocator
subjects:
- kind: ServiceAccount
  namespace: o11y-prom-collector
  name: prom-targetallocator

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: o11y-prom-collector
  name: prom-pod-annotations # discovers metrics by pod annotations
  labels:
    app.kubernetes.io/component: prom-targetallocator
    app.kubernetes.io/name: prom-collector
    {{- include "otel-collectors.metadataLabels" $ | nindent 4 }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels: {}
  podMetricsEndpoints:
  - relabelings: # https://github.com/prometheus-community/helm-charts/blob/2f1d889c6d5e7c3a73b61476b3efe7eed8385d35/charts/prometheus/values.yaml#L1109
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
      action: keep
      regex: "true"
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_scheme"]
      action: replace
      regex: (https?)
      targetLabel: __scheme__
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
      action: replace
      regex: (.+)
      targetLabel: __metrics_path__
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port", "__meta_kubernetes_pod_ip"]
      action: replace
      regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
      replacement: '[$2]:$1'
      targetLabel: __address__
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port", "__meta_kubernetes_pod_ip"]
      action: replace
      regex: (\d+);((([0-9]+?)(\.|$)){4})
      replacement: $2:$1
      targetLabel: __address__
