repository: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gorun/demo/kuard
tag: 0.7.100
aliases:
  - # https://hub.docker.com/r/damianagape/gorun-kuard
    repository: damianagape/gorun-kuard
  - # https://github.com/users/damianagape/packages/container/package/gogcp-kuard
    repository: ghcr.io/damianagape/gorun-kuard
