{{- if .Values.targetAllocator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-targetallocator"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: targetallocator
    {{- include "otelcol.metadataLabels" . | nindent 4 }}
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Namespace }}-{{ .Release.Name }}-targetallocator"
  labels:
    app.kubernetes.io/component: targetallocator
    {{- include "otelcol.metadataLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-targetallocator
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-targetallocator"
    namespace: "{{ .Release.Namespace }}"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Release.Name }}-pod-annotations" # discovers metrics by pod annotations
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: targetallocator
    {{- include "otelcol.metadataLabels" . | nindent 4 }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels: {}
  podMetricsEndpoints:
  - relabelings: # https://github.com/prometheus-community/helm-charts/blob/2f1d889c6d5e7c3a73b61476b3efe7eed8385d35/charts/prometheus/values.yaml#L1109
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
      action: keep
      regex: "true"
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_scheme"]
      action: replace
      regex: (https?)
      targetLabel: __scheme__
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
      action: replace
      regex: (.+)
      targetLabel: __metrics_path__
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port", "__meta_kubernetes_pod_ip"]
      action: replace
      regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
      replacement: '[$2]:$1'
      targetLabel: __address__
    - sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port", "__meta_kubernetes_pod_ip"]
      action: replace
      regex: (\d+);((([0-9]+?)(\.|$)){4})
      replacement: $2:$1
      targetLabel: __address__
{{- end }}
